name: Build, Publish Docker Image and Deploy Backend
run-name: Build, Publish Docker Image and Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image for backend
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/embarque-ja-backend:latest

      - name: SSH to VPS and deploy backend container
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            sudo docker stop backend || true
            sudo docker rm backend || true

            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/embarque-ja-backend:latest

            sudo docker run -d --env-file ~/app-config/.env --name backend -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/embarque-ja-backend:latest
